Algoritmo "semnome"
// 3 - Pedir para o usuário digitar quatro notas e imprimir na tela sua média aritmética.

Var
   n1, n2, n3, n4, m: real

Inicio
      Escreva ("Primeira nota: ")
      leia (n1)
      Escreva ("Segunda nota: ")
      leia (n2)
      Escreva ("Terceira nota: ")
      leia (n3)
      Escreva ("Quarta nota: ")
      leia (n4)
      
      m <- (n1 + n2 + n3 + n4) /2
      
      Escreval ("A media do aluno é: ",m)


Fimalgoritmo