Algoritmo "semnome"
// 7 - ler o nome de uma pessoa, a sua idade e o seu salário e mostrar as informações.





Var
   nome, idade : caracter
   s : real

Inicio
      Escreval ("Nome: ")
      leia (nome)
      escreval ("Idade: ")
      leia (idade)
      escreval ("Salario: ")
      leia (s)
      
      escreval ("Informaçoes do Usuario!")
      escreval (" ")
      Escreval ("O nome do funcionario é ",nome, " ,Idade: " ,idade, " e seu salario é " , s,".")
      


Fimalgoritmo