Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/02/2022
Var
// Seção de Declarações das variáveis 
   n : real

Inicio
      escreva ("digite um numero: ")
      leia (n)
      escreval ("Numero " ,n, " impresso na tela")


Fimalgoritmo