Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/02/2022
Var
 n1, n2 , m : real


Inicio
      escreva ("primeira nota: ")
      leia (n1)
      escreva ("segunda nota: ")
      leia (n2)

      m <- (n1 + n2) /2
      
      escreval ("a media é : ",m)


Fimalgoritmo