Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/02/2022

var
cf, pr, ci, pf : real

inicio
         escreva ("digite o custo")
         leia(cf)
         pr <- (cf *25)/100
         ci <- (cf*45)/100
         pf <- pr+ci+cf
         escreval (" O preço final ao consumidor é " ,pf )



Fimalgoritmo