Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/02/2022

var

   saldo, c : real

inicio
   escreva ("Insira o valor do cheque")
   leia (c)
   saldo <- 500
   saldo <- saldo – c
   escreval ("Seu saldo é ", saldo)



Fimalgoritmo