Algoritmo "1º"
// 1 - Pedir para o usuário digitar um número e imprimir este número na tela.

Var
   numero1 , numero2 : inteiro
   soma : real


Inicio
      escreva ("Digite um numero: ")
      leia (numero1)
      escreva ("Digite outro numero: ")
      leia (numero2)

      soma <- numero1 + numero2
      
      escreval ("A soma entre " ,numero1 , " e " ,numero2 , " é igual a :" ,soma)
Fimalgoritmo