Algoritmo "semnome"
//8 - Um cliente de um banco tem um saldo positivo de R$500,00.  Fazer um algoritmo que leia o cheque que entrou e calcule o saldo, mostrando (escrevendo) o saldo na tela.






Var

   saldo, cheque, saldo_atual : real

Inicio
      escreval("Digite o valor do cheque : ")
      leia(cheque)

       saldo <- 500,00
        saldo_atual <- saldo + cheque

         escreval("O seu saldo atual é : ", saldo_atual)

      


Fimalgoritmo