Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/03/2022
Var
   contador : inteiro


Inicio
   contador <- 0
   enquanto (contador <= 10)    faca
      escreval (contador)
      contador <- contador + 1
   fimenquanto


Fimalgoritmo