Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/03/2022
Var
   contador : inteiro


Inicio
   contador <- 10
   enquanto (contador >= 0)    faca
      escreval (contador)
      contador <- contador - 1
   fimenquanto
   escreval ("terminei de contar!")

Fimalgoritmo