Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2022
Var
   cont: inteiro
Inicio
   cont <- 100
   enquanto cont < 200 faca
      se cont mod 2 = 1 entao
         escreval(cont)
      fimse
      cont <- cont + 1
   fimenquanto
Fimalgoritmo